version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    default_labels:
      - "Meta: Automation"
      - "Actor: Dependabot"
      - "Type: Dependencies"
      - "Deps: Python"
    automerged_updates:
      - match:
          update_type: "semver:patch"
    commit_message:
      prefix: "chore"
      include_scope: true
    version_requirement_updates: "auto"
  # Keep Dockerfile up to date, batching pull requests weekly
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_labels:
      - "Meta: Automation"
      - "Actor: Dependabot"
      - "Type: Dependencies"
      - "Deps: Docker"
    automerged_updates:
      - match:
          update_type: "semver:patch"
    commit_message:
      prefix: "chore"
      include_scope: true
    allowed_updates:
      - match:
          update_type: "security"
