name: build
on:
  push:
    paths-ignore:
      - ".gitignore"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
      - ".dependabot/**"
      - "_config.yml"
  pull_request:
jobs:
  # lint everything
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [fmt-lint, flake8, mypy]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          curl -sSLO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python3 get-poetry.py --version 1.0.3
          echo "::add-path::$HOME/.poetry/bin"
          rm -f get-poetry.py
      - name: Install dependencies
        run: |
          echo ${PATH}
          which poetry
          poetry install -v --no-dev
          if [[ $LINTER == fmt-* ]]; then
            pip install black isort[pyproject] pytest responses
          else
            pip install "$LINTER"
          fi
        env:
          LINTER: ${{ matrix.linter }}
      - name: Lint
        run: poetry run make ${{ matrix.linter }}

  # Test on all platforms
  test:
    needs: lint
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        pythonVersion: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.pythonVersion }}
    - name: Install Poetry
      run: |
        curl -sSLO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        python3 get-poetry.py --version 1.0.3
        echo "::add-path::$HOME/.poetry/bin"
    - name: Install Dependencies
      run: |
        echo ${PATH}
        which poetry
        poetry install -v
    - name: Test
      run: poetry run make test

    - name: Build
      run: make dist

    - name: Export Version
      id: version
      run: |
        poetry run python3 ./scripts/getversion.py | tee -a VERSION.txt
        echo "::set-output name=VERSION::$(cat VERSION.txt)"

  # Build docker images
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfiles
        run: make docker-lint

      - name: Build Docker
        run: make docker-all
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Docker Login to Registry (GitHub)
        run: echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

      - name: Docker Login to Registry (DockerHub)
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: tprasadtp
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

      - name: Docker Push
        run: make docker-push
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

      - name: Docker Cleanup
        run: docker logout && rm -f ${HOME}/.docker/config.json
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
